apiVersion: 1

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    version: 1
    editable: true

      #  - name: Prometheus
      #    type: prometheus
      #    url: http://localhost:9090
      #    access: proxy
      #    isDefault: true
      #    version: 1
      #    editable: false